//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interests
    {
        public int InterestID { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
    }
}
